apiVersion: apps/v1
kind: Deployment
metadata:
  name: minor-deployment
  namespace: minor
  labels:
    app: op
spec:
  replicas: 2
  selector:
    matchLabels:
      app: op
  template:
    metadata:
      labels:
        app: op
    spec:
      containers:
      - name: minor-deployment
        image: krishna1708/minor_test1:latest
        ports:
        - containerPort: 80
      