apiVersion: v1
kind: Service
metadata:
  labels:
    app: op
  name: minor-svc
  namespace: minor
spec:
  ports:
  - port: 80
    protocol: TCP
    targetPort: 80
  selector:
    app: op
  type: NodePort